apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger
  namespace: tracing
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - tracing
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
  endpoints:
    - port: admin-http
      path: /metrics
      interval: 30s
