apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
    app.kubernetes.io/part-of: digiorg-core-platform
    app.kubernetes.io/component: logging
spec:
  selector:
    app: fluentd
  clusterIP: None
  ports:
    - name: prometheus
      port: 24231
      targetPort: 24231
      protocol: TCP
