apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://github.com/digiorg/core.git
    targetRevision: issue285-runtime-v9-20260724T122821Z
    path: platform/base/cnpg
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-db
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
