apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://jaegertracing.github.io/helm-charts
      chart: jaeger
      targetRevision: "3.x"
      helm:
        releaseName: jaeger
        valueFiles:
          - $values/platform/base/jaeger/values.yaml
    - repoURL: https://github.com/digiorg/core.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/digiorg/core.git
      targetRevision: HEAD
      path: platform/base/jaeger
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
