apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landingpage
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: digiorg-core-platform
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/digiorg/core.git
    targetRevision: HEAD
    path: platform/base/landingpage
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
