apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
  - repoURL: https://opensearch-project.github.io/helm-charts
    chart: opensearch
    targetRevision: 3.7.0
    helm:
      releaseName: opensearch
      valueFiles:
      - $values/platform/base/opensearch/values.yaml
  - repoURL: https://github.com/digiorg/core.git
    targetRevision: issue285-runtime-v9-20260724T122821Z
    ref: values
  - repoURL: https://github.com/digiorg/core.git
    targetRevision: issue285-runtime-v9-20260724T122821Z
    path: platform/base/opensearch
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-db
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    name: opensearch-cluster-master
    jqPathExpressions:
    - .spec.volumeClaimTemplates[]?.apiVersion
    - .spec.volumeClaimTemplates[]?.kind
    - .spec.volumeClaimTemplates[]?.spec.volumeMode
    - .spec.volumeClaimTemplates[]?.status
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
