apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-apps

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - services-configmap.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/digiorg/core-landingpage
    newTag: main
